// @ts-nocheck -- This self-contained function is serialized as the browser script.
function webClient(){
  const $=id=>document.getElementById(id);let socket,pc,queue=[],generation=0,sequence=Promise.resolve();const audio=$('audio');
  function stop(){generation++;if(socket){socket.onclose=null;socket.close();}socket=null;pc?.close();pc=null;queue=[];audio.pause();audio.srcObject=null;$('player').hidden=true;}
  async function refresh(){try{const r=await fetch('/sessions');if(!r.ok)throw Error('No se pudo cargar. Intentá nuevamente.');const sessions=await r.json();$('sessions').replaceChildren();$('empty').textContent=sessions.length?'':'No hay sesiones públicas activas. Volvé en un rato.';
    for(const s of sessions){const card=document.createElement('article'),title=document.createElement('h2'),info=document.createElement('p'),button=document.createElement('button');title.textContent=s.names.join(' × ');info.textContent=`EN VIVO · ${s.listeners}/${s.capacity} oyentes`;button.textContent=s.listeners>=s.capacity?'Completa':'Escuchar →';button.disabled=s.listeners>=s.capacity;button.onclick=()=>listen(s.id,title.textContent);card.append(title,info,button);$('sessions').append(card);}
  }catch(e){$('empty').textContent=e.message;}}
  function listen(id,name){stop();const gen=generation;$('player').hidden=false;$('title').textContent=name;$('status').textContent='Conectando audio…';
    // Unlock playback during the click; controls remain available if autoplay is blocked.
    audio.play().catch(()=>{});const url=new URL('/audience',location.href);url.protocol=location.protocol==='https:'?'wss:':'ws:';url.searchParams.set('id',id);socket=new WebSocket(url);
    const send=m=>{if(socket?.readyState===1)socket.send(JSON.stringify(m));};
    socket.onmessage=event=>{sequence=sequence.then(async()=>{if(gen!==generation)return;const m=JSON.parse(event.data);
      if(m.type==='audience.ready'){pc=new RTCPeerConnection({iceServers:m.iceServers});pc.onicecandidate=e=>{if(e.candidate)send({type:'audience.ice',candidate:e.candidate.toJSON()});};pc.ontrack=e=>{audio.srcObject=new MediaStream([e.track]);audio.play().catch(()=>$('status').textContent='Tocá ▶ para activar el audio.');};pc.onconnectionstatechange=()=>{if(gen!==generation)return;$('status').textContent=pc.connectionState==='connected'?'En vivo · mezcla de ambos DJs':pc.connectionState==='failed'?'No se pudo conectar el audio. Volvé a entrar.':'Conectando audio…';};}
      if(m.type==='audience.offer'){await pc.setRemoteDescription({type:'offer',sdp:m.sdp});for(const t of pc.getTransceivers())t.direction='recvonly';for(const c of queue)await pc.addIceCandidate(c);queue=[];await pc.setLocalDescription(await pc.createAnswer());send({type:'audience.answer',sdp:pc.localDescription.sdp});}
      if(m.type==='audience.ice'){if(pc?.remoteDescription)await pc.addIceCandidate(m.candidate);else queue.push(m.candidate);}
    }).catch(()=>$('status').textContent='Error de conexión. Salí y volvé a entrar.');};
    socket.onclose=e=>{if(gen!==generation)return;pc?.close();audio.srcObject=null;$('status').textContent=e.reason||'Se cortó la conexión. Volvé a entrar para reconectar.';void refresh();};socket.onerror=()=>{$('status').textContent='No se pudo conectar al servidor.';};
  }
  $('leave').onclick=()=>{stop();void refresh();};$('refresh').onclick=refresh;window.addEventListener('pagehide',stop);void refresh();setInterval(refresh,15000);
}
export const listenScript=`(${webClient.toString()})();`;
export const listenPage=`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RemoteB2B · En vivo</title><style>
*{box-sizing:border-box}body{margin:0;background:#101713;color:#eef2e9;font:16px system-ui,sans-serif}main{max-width:980px;margin:auto;padding:48px 24px}header{letter-spacing:3px;color:#a9cd85;font-weight:800}h1{font-size:clamp(36px,7vw,64px);letter-spacing:-2px;margin-bottom:12px}p{color:#b8c4b9;line-height:1.6}#sessions{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px;margin-top:32px}article,#player{border:1px solid #354636;border-radius:16px;padding:24px;background:#19231c}h2{overflow-wrap:anywhere}button{background:#b9db91;color:#142015;border:0;border-radius:8px;padding:13px 20px;font:600 16px system-ui;cursor:pointer}button:disabled{opacity:.45;cursor:default}button:focus-visible{outline:3px solid white;outline-offset:4px}.ghost{background:transparent;color:#c6d9ba;border:1px solid #526449}#player{margin:28px 0}audio{width:100%;margin:12px 0 20px}small{display:block;margin-top:40px;color:#8fa18e}[hidden]{display:none!important}</style></head><body><main><header>REMOTE ↔ B2B / LIVE</header><h1>La cabina está abierta.</h1><p>Elegí una sesión y escuchá a los DJs en vivo. Sin instalar nada y sin activar tu micrófono.</p><section id="player" hidden><h2 id="title"></h2><p id="status" role="status"></p><audio id="audio" controls autoplay></audio><button id="leave" class="ghost">Dejar de escuchar</button></section><button id="refresh" class="ghost">Actualizar sesiones</button><p id="empty" role="status">Buscando sesiones…</p><div id="sessions"></div><small>Hasta 4 oyentes por sesión. La transmisión termina cuando el creador deja de publicar.<br>La mezcla se genera en la PC del creador; la demora depende de las conexiones de ambos DJs.</small></main><script src="/listen.js"></script></body></html>`;
